# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: policy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='policy.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cpolicy.proto\"9\n\x10raw_action_entry\x12\x0e\n\x06offset\x18\x01 \x02(\x05\x12\x15\n\rreplace_bytes\x18\x02 \x02(\t\"#\n\x12redact_match_entry\x12\r\n\x05magic\x18\x01 \x02(\t\"d\n\x12\x64\x65ref_action_entry\x12\x0e\n\x06offset\x18\x01 \x02(\x05\x12\x1d\n\x02ra\x18\x02 \x01(\x0b\x32\x11.raw_action_entry\x12\x1f\n\x02\x64\x61\x18\x03 \x01(\x0b\x32\x13.deref_action_entry\"\x8b\x01\n\x11redact_task_entry\x12\"\n\x05match\x18\x01 \x02(\x0b\x32\x13.redact_match_entry\x12&\n\x0braw_actions\x18\x02 \x03(\x0b\x32\x11.raw_action_entry\x12*\n\rderef_actions\x18\x03 \x03(\x0b\x32\x13.deref_action_entry\"7\n\x12redact_tasks_entry\x12!\n\x05tasks\x18\x01 \x03(\x0b\x32\x12.redact_task_entry')
)




_RAW_ACTION_ENTRY = _descriptor.Descriptor(
  name='raw_action_entry',
  full_name='raw_action_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='raw_action_entry.offset', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replace_bytes', full_name='raw_action_entry.replace_bytes', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=73,
)


_REDACT_MATCH_ENTRY = _descriptor.Descriptor(
  name='redact_match_entry',
  full_name='redact_match_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='magic', full_name='redact_match_entry.magic', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=110,
)


_DEREF_ACTION_ENTRY = _descriptor.Descriptor(
  name='deref_action_entry',
  full_name='deref_action_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='deref_action_entry.offset', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ra', full_name='deref_action_entry.ra', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='da', full_name='deref_action_entry.da', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=212,
)


_REDACT_TASK_ENTRY = _descriptor.Descriptor(
  name='redact_task_entry',
  full_name='redact_task_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match', full_name='redact_task_entry.match', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_actions', full_name='redact_task_entry.raw_actions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deref_actions', full_name='redact_task_entry.deref_actions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=354,
)


_REDACT_TASKS_ENTRY = _descriptor.Descriptor(
  name='redact_tasks_entry',
  full_name='redact_tasks_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='redact_tasks_entry.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=411,
)

_DEREF_ACTION_ENTRY.fields_by_name['ra'].message_type = _RAW_ACTION_ENTRY
_DEREF_ACTION_ENTRY.fields_by_name['da'].message_type = _DEREF_ACTION_ENTRY
_REDACT_TASK_ENTRY.fields_by_name['match'].message_type = _REDACT_MATCH_ENTRY
_REDACT_TASK_ENTRY.fields_by_name['raw_actions'].message_type = _RAW_ACTION_ENTRY
_REDACT_TASK_ENTRY.fields_by_name['deref_actions'].message_type = _DEREF_ACTION_ENTRY
_REDACT_TASKS_ENTRY.fields_by_name['tasks'].message_type = _REDACT_TASK_ENTRY
DESCRIPTOR.message_types_by_name['raw_action_entry'] = _RAW_ACTION_ENTRY
DESCRIPTOR.message_types_by_name['redact_match_entry'] = _REDACT_MATCH_ENTRY
DESCRIPTOR.message_types_by_name['deref_action_entry'] = _DEREF_ACTION_ENTRY
DESCRIPTOR.message_types_by_name['redact_task_entry'] = _REDACT_TASK_ENTRY
DESCRIPTOR.message_types_by_name['redact_tasks_entry'] = _REDACT_TASKS_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

raw_action_entry = _reflection.GeneratedProtocolMessageType('raw_action_entry', (_message.Message,), dict(
  DESCRIPTOR = _RAW_ACTION_ENTRY,
  __module__ = 'policy_pb2'
  # @@protoc_insertion_point(class_scope:raw_action_entry)
  ))
_sym_db.RegisterMessage(raw_action_entry)

redact_match_entry = _reflection.GeneratedProtocolMessageType('redact_match_entry', (_message.Message,), dict(
  DESCRIPTOR = _REDACT_MATCH_ENTRY,
  __module__ = 'policy_pb2'
  # @@protoc_insertion_point(class_scope:redact_match_entry)
  ))
_sym_db.RegisterMessage(redact_match_entry)

deref_action_entry = _reflection.GeneratedProtocolMessageType('deref_action_entry', (_message.Message,), dict(
  DESCRIPTOR = _DEREF_ACTION_ENTRY,
  __module__ = 'policy_pb2'
  # @@protoc_insertion_point(class_scope:deref_action_entry)
  ))
_sym_db.RegisterMessage(deref_action_entry)

redact_task_entry = _reflection.GeneratedProtocolMessageType('redact_task_entry', (_message.Message,), dict(
  DESCRIPTOR = _REDACT_TASK_ENTRY,
  __module__ = 'policy_pb2'
  # @@protoc_insertion_point(class_scope:redact_task_entry)
  ))
_sym_db.RegisterMessage(redact_task_entry)

redact_tasks_entry = _reflection.GeneratedProtocolMessageType('redact_tasks_entry', (_message.Message,), dict(
  DESCRIPTOR = _REDACT_TASKS_ENTRY,
  __module__ = 'policy_pb2'
  # @@protoc_insertion_point(class_scope:redact_tasks_entry)
  ))
_sym_db.RegisterMessage(redact_tasks_entry)


# @@protoc_insertion_point(module_scope)
